### ISSUE TITLE
Typography Notes

### ISSUE THREAD

**Issue by iamnewton** [AssemblerUI/assembler#3]
- [Vertical Rhythm](http://compass-style.org/reference/compass/typography/vertical_rhythm/)
- [Google Search](https://www.google.com/search?newwindow=1&safe=off&q=math+for+setting+typographical+leading&es_sm=91&biw=1280&bih=773&dpr=2&cad=cbv&sei=5wr1VOPMGcv3oASkiYKwCQ)
- [Golden Ratio](http://www.pearsonified.com/typography/)

helpers:

``` css
.hyphenate {
    word-wrap: break-word;
    hyphens: auto;
}
/* helps with fonts that look a bit chunky on MacOS vs other platforms/OS's */
.skinnify {
    -webkit-font-smoothing: antialiased; 
    -moz-osx-font-smoothing: grayscale;
}
.unskinnify {
    -webkit-font-smoothing: auto; 
    -moz-osx-font-smoothing: auto;
}
```
